language: java
jdk: oraclejdk12

services:
  - mysql
  
before_install:
  - chmod +x mvnw
  - mysql -u root -e "CREATE DATABASE restaurante_teste;"
  - mysql -u root -e "CREATE user 'userteste'@'%' identified by '123456';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON restaurante_teste.* TO 'userteste'@'%';";